# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  default_platform(:ios)


  def updateVersion(options)
    if options[:version]
      version = options[:version]
    else
      version = prompt(text: "버전을 입력해주세요 (ex 1.0.0) : ")
    end

    re = /\d+.\d+.\d+/
    versionNum = version[re, 0]

    if (versionNum)
      increment_version_number(
        version_number: versionNum
      )
    elsif (version == 'major' || version == 'minor' || version == 'patch')
      increment_version_number(
        bump_type: version
      )
    elsif (version == 'maintain')
    else
      UI.user_error!("[ERROR] Wrong version!!!!!!")
    end
  end

  desc "build app"
  lane :build do |options|
    cert
    sigh(force: true)
    updateVersion(options)

    increment_build_number(xcodeproj: "myApp.xcodeproj")
    build_app(workspace: "myApp.xcworkspace", scheme: "myAppScheme")
  end


  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    match(
      type: "appstore",
      app_identifier: 'org.reactjs.native.example.JungChongMoo',
      readonly: true
    )
    updateVersion(options)

    increment_build_number(xcodeproj: "JungChongMoo.xcodeproj")
    build_app(workspace: "JungChongMoo.xcworkspace", scheme: "JungChongMoo")
    upload_to_testflight
  end
end

